### ISSUE TITLE
Clarifying spelling inheritance?

### ISSUE THREAD

**Issue by amyq** [vale-cli/vale#107]
When building out our tests, I ran into some issues with spelling ignore files that may or may not be a bug, but it didn't work the way I expected.

We have multiple styles that we layer atop each other, so we can make clear whether a rule comes from the Microsoft style guide, or our additions + extensions to the Microsoft guide. As a result, I created a Spelling.yml file for each style, with an ignore file for each, expecting that the list of ignored words would be the total of ignore-file-A + ignore-file-B. 

When we implemented the spelling tests, though, only the words in ignore-file-B were skipped during spellcheck. 

Is this expected behavior or did I misconfigure the .yml files in some way?

**Comment by jdkato** [comment]
Here's a minimal example of how Vale handles a case like this:

- Let's say we have a Markdown file with three words in it: `consectetur adipisicing elit`;
- a style `A` that implements a spelling rule that ignores `consectetur`; and
- a  style `B` that implements a spelling rule that ignores `adipisicing`.

If we were to inherit only from `A` (i.e., `BasedOnStyles = A`), we would expect Vale to flag both `adipisicing` and `elit` but ignore `consectetur`. If we were to inherit only from `B` (i.e., `BasedOnStyles = B`), we would expect Vale to flag both `consectetur` and `elit` but ignore `adipisicing`.

If we were to inherit from both (i.e., `BasedOnStyles = A, B`), the above expectations *don't* change: the presence of style `A` doesn't change the behavior of style `B` and vice versa. So, we would expect Vale to flag `consectetur` (`B.Spelling`), `adipisicing` (`A.Spelling`), and `elit` twice (`A.Spelling` and `B.Spelling`).

This (IMO) is generally the correct way to handle style inheritance because, for example, `A` could also specify that its headings should be in title case while `B` wants sentence case. In other words, it's not possible to make styles "compatible" without violating the guidelines of one (of course, you can manually do this in your `.vale.ini` file by selectively ignoring parts of a certain style).

---

So, in your case, the list of ignored words is technically ignore-file-A + ignore-file-B. It's just that A doesn't take into consideration B and B doesn't take into consideration A.

My suggestion would be to use your individual ignore files (from Microsoft and the extensions) in a rule implemented in the extension style:

```yaml
extends: spelling
message: "Did you really mean '%s'?"
ignore:
  - Microsoft.txt
  - custom.txt
```

**Comment by amyq** [comment]
Thanks! That's exactly what we ended up doing, but it felt odd mixing styles like that. It was worth checking to make sure I was doing it right.
