### ISSUE TITLE
ignore certain files

### ISSUE THREAD

**Issue by MaliusArth** [vale-cli/vale#131]
Is it possible to ignore certain files/folders and file types in the .vale file?
I would like to ignore .sty or .bst files in my LaTeX project and limit linting to specific subdirectories.
Something like .gitignore would be very powerful, could as well be part of the .vale file.
example usage:
```

IgnorePaths: (relative to .vale file)
*.bst
*_partial_name.sty
research/*
notes/*.txt
```

- OS: Linux Mint
- Install method: direct download + vs code extension
- Vale version: 1.4.2

Thanks!

**Comment by MaliusArth** [comment]
I tried specifying a spelling style extension with ignore paths but that doesn't seem to support wildcards
As far as I understood it's relative to the StylesPath, hence the ../ prefixes
```
extends: spelling
ignore:
  - ../*.bst
  - ../*.sty
  - ../research/*
  - ../latex/*
  - ../tools/*
```

**Comment by jdkato** [comment]
Vale typically works in the other direction: instead of listing what files you'd like to ignore, you explicitly tell it what to lint.

This can be seen in the example `.vale.ini` file:

```ini
# This goes in a file named either `.vale.ini` or `_vale.ini`.

StylesPath = path/to/some/directory
MinAlertLevel = warning # suggestion, warning or error

# Only Markdown and .txt files; change to whatever you're using.
[*.{md,txt}]
# List of styles to load.
BasedOnStyles = proselint, write-good, Joblint
# Style.Rule = {YES, NO, suggestion, warning, error} to
# enable/disable a rule or change its level.
write-good.E-Prime = NO
```
Using the above, everything but `.md` and `.txt` files is ignored. The approach is similar with directories: just call Vale with the specific arguments, such as `$ vale dir1 dir2`.

If you need more control than this, I'd recommend wrapping Vale in a shell script that uses the appropriate tools (see [here](https://unix.stackexchange.com/questions/358270/find-files-that-are-not-in-gitignore) for some ideas).

--- 

The `ignore` key in `Spelling` rules specifies the location (relative to `StylesPath`) of files that contain words to ignore during spell-checking; not files or directories to ignore in general.

**Comment by MaliusArth** [comment]
I see, in that case it would be great to have the possibility to pass command line arguments to vale via the vs code vale extension

**Comment by jdkato** [comment]
I don't maintain the extension, so you'll probably want to open an issue over there.

**Comment by MaliusArth** [comment]
Oh right, sorry, I assumed it was part of this repo
