### ISSUE TITLE
Is it possible to override the MinAlertLevel from the CLI?

### ISSUE THREAD

**Issue by felicitymay** [vale-cli/vale#138]
I'd like the benefit of suggestions while writing, but only getting errors reported in Git reviews, without maintaining two different configuration files. Otherwise there's a danger that they get out of step. 

I had a look at the usage information, hoping that there was a flag for Vale so that you could override the `MinAlertLevel` when you run it from the command line. That way, you could have a single `.vale.ini` file which reported suggestions in your IDE, but when you ran automated tests on pull requests you could override this and just report errors.

Can you think of a workaround for this use case?

**Comment by ArtFlag** [comment]
I was trying to do the exact same thing just now. Perfect timing, I support your suggestion.

What you could do is have 2 config files:

- one with a default name that Vale looks for automatically (`some/file/path/.vale.ini`), used by your IDE.
- one dedicated for CI builds. You can then call Vale with `vale --config='some/file/path/.vale_ci.ini'`

It's not ideal since you duplicate the config file only to change the `minalertlevel` param but that would be one way to do it.

**Comment by jdkato** [comment]
I'll add a `--minAlertLevel` flag in the next release.

**Comment by ArtFlag** [comment]
Super fast support 🎉  Thanks @jdkato 👍

**Comment by felicitymay** [comment]
Wow! Thanks so much @jdkato

**Comment by jdkato** [comment]
This is available in [`v1.7.0`](https://github.com/errata-ai/vale/releases/tag/v1.7.0).
