### ISSUE TITLE
Support look ahead/behind expressions

### ISSUE THREAD

**Issue by ArtFlag** [vale-cli/vale#139]
Hi, 

I'm trying to set up a substitution style. This word can be part of some text, or some rst syntax (label, links...).

Here is the style:
```yaml
extends: substitution
message: "Use '%s' instead of '%s'"
ignorecase: true
level: error
swap:
  (?<!\S)table(?!\S): "cushion"
  \btable\b: "chair"
```
I'm interested in the `table -> cushion` check.

Then here is a test file:
```rst
That's a non-table. That's a table-link.
2 tables, no weird-table. Only 1 table should be replaced.
```

Here is the output that I get from Vale:

```console
source/test.rst
 1:14  error  Use 'chair' instead of 'table'  proj.Variables
 1:30  error  Use 'chair' instead of 'table'  proj.Variables
 2:20  error  Use 'chair' instead of 'table'  proj.Variables

✖ 3 errors, 0 warnings and 0 suggestions in 1 file.
```

These 3 results are correct, but I'm missing one. I should see 
`Use 'cushion' instead of 'table'  proj.Variables` on line 2.

This leads me to think that Vale does not support look behind/ahead expressions (the same regexp works fine on regexp101.com).
If it is the case, I would like to submit this as a feature request. 

Thanks for the good work with this tool! 

- Homebrew
- Vale 1.60

**Comment by jdkato** [comment]
This is a limitation (or feature, as some would claim) of the Go programming language's [`regexp`](https://golang.org/pkg/regexp) package. When using regex101, you'll want to switch the flavor to "Golang" to make sure you're using the same library as Vale. Fortunately, I've found that lookarounds are rarely actually needed for Vale's use cases.

In this case, though, I'm not sure that I understand the goal of the rule. Could you describe when you want 'chair' vs. 'cushion'? 

(Currently, it appears that you want 'cushion' whenever 'table' is surrounded by whitespace -- but `\b` also matches whitespace.)

See the [extension point documentation](https://errata-ai.github.io/vale/styles/#creating-a-style) for more information.

**Comment by ArtFlag** [comment]
What a shame. In my case, I just wanted to have a way to identify `table` that is not part of any pattern (email, urls, rst labels) and report it (the `cushion` case, the other `chair` case was just for testing). 

I ended up using   `'(?:[^-@.])table(?:[^-]\.?\,?)'` which seems to work for now.

I would suggest adding a note to the docs to avoid further questions (even though this issue should come up in ppl's search results). I can send a PR if you want.

**Comment by jdkato** [comment]
There's a callout in the docs that mentions this already (see the link in my previous post). 

Also, in general, you shouldn't have to consider markup syntax for [supported formats](https://errata-ai.github.io/vale/formats/#overview) when writing rules. Vale handles the common cases (e.g., code blocks, URLs, etc.) and provides ways to handle [non-standard cases in your config file](https://errata-ai.github.io/vale/formats/#non-standard-markup).

---

With regards to this rule in particular, it's only a matter of getting the word boundaries correct. [By default](https://errata-ai.github.io/vale/styles/#creating-a-style), Vale adds `\b`s to entries in `substitution`. Since this will match tokens like 'table' in 'non-table', we can change it to `\s`:

```yaml
extends: substitution
message: "Use '%s' instead of '%s'"
ignorecase: true
level: error
# We're using our own boundaries:
nonword: true
swap:
  '\stable[\s.,]': chair
```

(Finally, for what it's worth, I've written a lot of rules and I've found that the lack of lookarounds generally results in cleaner and faster regular expressions more often than it poses any significant limitations.)
