### ISSUE TITLE
Determining why Vale isn't checking part of a file?

### ISSUE THREAD

**Issue by amyq** [vale-cli/vale#146]
- OS: macOS
- Install method: homebrew
- Vale version: 1.7.0

We’re using the sphinx-tabs project (https://github.com/djungelorm/sphinx-tabs) and in some - not all - files that use in-page tabs, Vale does not check the items inside this structure:

```

   .. tab:: foo

       Content here

   .. tab:: bar

       More content here
```

(I'm happy to provide the full file privately but really shouldn't paste the whole thing in here, because it involves a project that hasn't launched yet)

Running Vale with the `--ignore-syntax` flag in the CLI runs the tests that can be completed line-by-line, but I’m not sure how to proceed from here.

```
$ vale --no-wrap filename.rst
✔ 0 errors, 0 warnings and 0 suggestions in 1 file.

$ vale --ignore-syntax --no-wrap filename.rst

 filename.rst
 18:53  warning     'only' is a weasel word!                write-good.Weasel
 35:11  suggestion  'be indexed' looks like passive voice.  microsoft.Passive
 36:26  suggestion  Use "won't" instead of "will not".      microsoft.Contractions
 41:17  error       Spelling check: 'signin'?               acquia.Spelling
 62:32  suggestion  Use "doesn't" instead of "does not".    microsoft.Contractions
 62:41  warning     'currently' is a weasel word!           write-good.Weasel
```

**Comment by jdkato** [comment]
The issue is, essentially, that Vale supports reStructuredText *but not necessarily Sphinx's dialect* of reStructuredText. The reason that I have to make such an unnecessary distinction is due to an apparent lack of tooling: Vale simply needs to be able to convert a standalone reStructuredText file into HTML, but there doesn't appear to be an adequate method for doing this. 

The two options are `rst2html` (what Vale currently uses) and Pandoc, but neither handles Sphinx-specific directives well. If you run `rst2html.py --quiet <your file with sphinx-tabs>.rst`, the problem will likely become apparent (this has also been discussed in https://github.com/errata-ai/vale/issues/119#issuecomment-519773411 and #140). 

FWIW, GitHub (which has nearly identical parsing needs to Vale and also uses `rst2html`) [recommends the following](https://github.com/github/markup/blob/f3531a558933c819dc4c1d8a10603fb424e2f612/lib/github/commands/rest2html#L66-L74):

```python
# Recommended practice for repositories with rst files:
#  - If github is the preferred viewer for the rst files (e.g. README.rst),
#    then design the files to properly display for github.  E.g., do not
#    include unknown directives or restructuredText comments.
#  - If github is NOT the preferred viewer for the rst files (e.g.
#    the files are designed to be used with sphinx extensions at readthedocs)
#    then include a restructuredText comment at the top of the file
#    explaining that the document will display much more nicely with its
#    preferred viewer, e.g. at readthedocs.
```
I'd much rather use Sphinx directly than `rst2html` (as I think Sphinx is really the *only* reason to be using reStructuredText at this point), but it's unclear how (or if) Vale can use Sphinx to build standalone HTML files without having to care about the greater project structure. In other words, what Vale needs is `sphinx-build single-file.rst`.

**Comment by jdkato** [comment]
> I'd much rather use Sphinx directly than `rst2html` (as I think Sphinx is really the _only_ reason to be using reStructuredText at this point), but it's unclear how (or if) Vale can use Sphinx to build standalone HTML files without having to care about the greater project structure. In other words, what Vale needs is `sphinx-build single-file.rst`.

I've had more time to look into this and I don't think there's a good way to fully support Sphinx through `rst2html`.

So, in other words, I think this is more of a feature request than a bug report: Vale supports reStructuredText, but not Sphinx's superset of the format.

#147 tracks adding support for Sphinx.
