### ISSUE TITLE
Having trouble with matching with regex

### ISSUE THREAD

**Issue by tperry-r7** [vale-cli/vale#196]
I'm having a problem with having valid regex
https://regex101.com/r/x7KqSh/2, but Vale not matching. This has happened a few times, but using this one as an example. Is there any reason it won't return a match. 

For example, I am matching markdown directly to look for italics. 

```
extends: existence
message: Avoid Italics
ignorecase: true
level: warning
nonword: true
raw: 
  - (?:^|(<=\s))(?:\*\s*([^*]+)\s*?\*|\*{3}\s*([^*]*)\s*\*{3})(?:$|(=\s))
```
I've got the result I want in golang, but Vale doesn't return anything. 

<img width="1312" alt="Screen Shot 2020-04-27 at 3 39 30 PM" src="https://user-images.githubusercontent.com/54866039/80418660-5f663c00-889d-11ea-91c0-2068d2c50b98.png">

**Comment by jdkato** [comment]
As with #193, you'll want to use `scope: raw` (available since v2.1.0) whenever you're trying to match markup syntax (e.g., `*`) itself.

That said, this really isn't what Vale is currently designed to do (it's designed for format-agnostic, *prose*-related rules); see https://github.com/errata-ai/vale/issues/194#issuecomment-617626667 and https://github.com/errata-ai/vale/issues/73#issuecomment-407515866 for more detailed explanations.
