### ISSUE TITLE
Generate a human readable style guide from the YML

### ISSUE THREAD

**Issue by plaindocs** [vale-cli/vale#20]
Would be a nice enhancement.

**Comment by jdkato** [comment]
Yeah, I agree that this would be nice. It would be a good way to ensure that Vale stays up-to-date with the actual style guide (versus having to edit two things for every change).

I was thinking that, in addition to the supported keys (e.g., `message` and `description`), Vale could render comments from the definition files. This would be similar to how API docs are rendered  from things like Javadoc.

**Comment by plaindocs** [comment]
Right.

The tricky thing will be making it useful. 

Or of course add specific fields for generating the guide instead of comments.

**Comment by jdkato** [comment]
I've given this more thought and I think it's beyond the scope of this project. 

There's no doubt that it'd be nice to have Vale synced with a human-readable style guide, but I think it would be best to come at this from the other direction: since all of Vale's style details are stored in easily accessible YAML files, it shouldn't be difficult to incorporate them into an existing documentation system (e.g., Sphinx/Python or AsciiDoctor/Ruby). This offloads all details about format, styling, and rendering to the user, which I think is the most flexible way to do this.
