### ISSUE TITLE
Apostrophe in  substitution key not having effect

### ISSUE THREAD

**Issue by rorokaloom** [vale-cli/vale#206]
Perhaps I'm doing something wrong here, I'd like to simply check for contractions and Vale doesn't seem to be picking it up. Using Antora to generate adocs to HTML via it's built-in generator. Vale is working on outputted HTML.

- Run as docker
- Vale version 2.2.0

```
extends: substitution
message: Use '%s' instead of '%s'
level: error
ignorecase: true
nonword: true
swap:
  aren't: are not
```

```
# This goes in a file named either `.vale.ini` or `_vale.ini`.

StylesPath = build/vale/styles
MinAlertLevel = warning

# Only HTML files; change to whatever you're using.
[*.{html}]

# List of styles to load.
# BasedOnStyles = proselint, write-good, Joblint, Default
BasedOnStyles = Default
```

Generated HTML seems to be the culprit, how would I solve this?
```
<div class="paragraph">
<p>This sentence has aren&#8217;t in it.</p>
</div>
```

**Comment by jdkato** [comment]
I would suggest running Vale on the AsciiDoc content rather than the generated HTML (the same goes for #207).

**Comment by rorokaloom** [comment]
This doesn't seem to work even when run on the .adoc files... Seems like the apostrophe is not being picked up. Is there something I need to add here? I have an adoc as follows:
```
= Introduction

Aren't you right?
```
Do I need to escape the quote or something?

**Comment by jdkato** [comment]
You're right -- the problem here is the Asciidoctor converts the apostrophe into a "smart" character under the hood, which means your rule (which uses a regular character) won't match. If you use a smart character in your rule, then Vale won't be able to find the word in the source document because it was written with a regular character.

The only way for this to work at the moment is to use a smart character in the document and the rule.

I'm not sure exactly how Vale should handle this (it'd nice if we could disable the behavior, but that doesn't seem to be possible?)

Also related to #136, #148, #226.

**Comment by jdkato** [comment]
I've given this more thought and I think the best way to handle this (short of being able to disable the behavior from Asciidoctor's side) is to assume that all apostrophes are 'dumb'.

This will mean that rules specifically targeting smart quotes (such as seen in #136) won't work on AsciiDoc files, but all other rules will. I think this makes the most sense, as most users will be writing 'dumb' apostrophes in their content anyway.
