### ISSUE TITLE
Silence duplicates?

### ISSUE THREAD

**Issue by coogle** [vale-cli/vale#215]
Not an issue, but more of an enhancement request. Would it be reasonable to include a new key for style definitions that indicates that it should only be displayed once in the output?

```
extends: existence
message: "[CROSSLINK: %s] Have you looked for a relevant link?"
ignorecase: true
level: suggestion
onlyonce: true
tokens:
  - MQTT
  - Home Assistant
  - ESP8266
  - DMA-BUF
```

The use-case is creating a style rule to hint that cross-linking against other content might be useful in the text based on the existence of keywords. I.e. if the content talks about MQTT, it would be valuable to suggest they cross-link to another article on MQTT as well. This works okay, the issue of course being every time the content talks about MQTT it repeats the message unnecessarily.

This is something I would be potentially willing to take a stab at implementing myself if it's otherwise reasonable and/or I can grok the source well enough to do so.

**Comment by jdkato** [comment]
This is the kind of problem that [`conditional`](https://errata-ai.gitbook.io/vale/getting-started/styles#conditional) is supposed to be able to solve.

Can you share an example of a cross-link? Is it simply a link like `[MQTT](...)`?

**Comment by brest-amzn** [comment]
Can you provide an example of how to use conditional to only catch the first instance of a pattern?
For example, let's say I only wanted to flag the first instance of the word "select" in a file.

**Comment by jdkato** [comment]
@brest-amzn: This is a different problem than the one discussed above: the idea for the above problem is that the first instance of "MQTT" should be written as `[MQTT](...)` whereas subsequent instances would just be "MQTT." In other words, there's a condition (the presence of a cross-link) that needs to be met.

If there's no uniquely identifying feature for the first instance of "select," then this isn't currently supported. Could you describe your motivation for only wanting to flag the first instance of a pattern?

**Comment by brest-amzn** [comment]
In some cases, there is useful information we want to convey that does not have a binary fix. Flagging every instance of the word causes too much visual noise. For my example, in this case, I want to remind writers when to use "select" vs "click".  

extends: existence
message: "Use \'select\' for choosing among items in a list or menu. Use \'click\' for buttons"
ignorecase: true
level: suggestion
tokens:
  - select
  - click

However, a single page and set of instructions might have the word select or click 25 + times on it –  since the warning will persist (there is no real way to "fix" the error), then it shows the error 25 times. It would be nice if it only flagged the first instance of the word. The writer would still read it at some point and it will prompt them to think about the tip while writing the rest of the document.

**Comment by jdkato** [comment]
I see -- I'll look into adding something along the lines of coogle's idea above in the next release.

**Comment by jdkato** [comment]
As of `v2.3.0`, this is now available -- you can control how many times a rule will raise an alert by specifying a value for `limit`:

```yaml
extends: existence
message: "Don't use '%s'."
level: error
limit: 1
tokens:
  - Token
```
A new version of Vale Server will be release soon (next week) with Vale `v2.3.0`, too.

**Comment by brest-amzn** [comment]
Sounds great, thanks!
