### ISSUE TITLE
Support for linting json and yaml content. 

### ISSUE THREAD

**Issue by plaindocs** [vale-cli/vale#24]
A lot of static site and documentation builders have content in json / yaml.

**Comment by jdkato** [comment]
The reason this doesn't exist currently is because I thought writing regexp in JSON was too much of a pain (with all the escaping you have to do). Most people will probably just be writing normal strings, though, so maybe it wouldn't be such a big deal.

(Also, FWIW, JSON is a supported *output* format.)

**Comment by plaindocs** [comment]
Yeah, I'm definitely talking input not output. 

Surely you'd parse the json, and just check the strings themselves, not the whole file, which would make the regex much easier?

**Comment by jdkato** [comment]
We're talking about supporting writing rules (currently YAML) in JSON right?

If that's the case, I meant that I think it's more difficult to use from a *user* standpoint since you have to remember more syntax requirements (e.g., the aforementioned escaping).

That said, I'm not necessarily against supporting it&mdash;so I'll leave this open.

**Comment by plaindocs** [comment]
Ah no, not at all. Sorry, I'll try to be more clear. 

We have json content that gets parsed into rst. So I'd like to check it. I mentioned yaml because if you use Jekyll and markdown that kind of configuration is mostly in yaml

**Comment by jdkato** [comment]
Oh, I see.

In this case, yeah, I agree.

**Comment by jdkato** [comment]
I've changed Vale's default behavior when given an "unrecognized" file type: it now falls back to simply linting line-by-line.

I think this is a more sane default in general, and it's also probably sufficient for most data interchange/serialization formats.

Closing this for now...

**Comment by plaindocs** [comment]
Sounds good to me.

Although if you have a ton of json files and you only want to check some of them we may run into issues later. But this fixes my current needs for sure.

Thanks!

**Comment by jdkato** [comment]
You should still be able to control which JSON files are linted via `--glob` or your config file. In fact, you'll need to update the latter with something like:

```ini
[*.{md,rst,txt,json}]
```
