### ISSUE TITLE
Vale GitHub check should ignore the stuff put in the code block

### ISSUE THREAD

**Issue by MichalMaler** [vale-cli/vale#244]
Info:
Linux, Status: Downloaded newer image for jdkato/vale:latest, vale version v2.1.0

Hello, 
vale should ignore the stuff put in the code block. In this example, it returns some errors regarding the proper use of the `api` term, but it is always a part of a URL and always inside the code block.

[1] 85:22   error       Did you really mean 'api'?      Vale.Spelling            
[2] 85:22   error       Use either 'or' or 'and' in     IBM.Slash                
                     'api/user'    

[1]
[subs="+quotes,macros,attributes"]
----
$ curl -X GET \
  --header 'Authorization: Bearer __<user-token>__' \
  'pass:c,m,a,q[+https:+//__<{prod-host}>__]/api/user/find?email=__<email>__'
----

[2]
----
$ curl -X GET \
  --header 'Authorization: Bearer __<user-token>__' \
  'https://che-vp-che.apps.che-dev.x6e0.p1.openshiftapps.com/api/user/find?name=vparfono'
----

Thank you for your time and for fixing this! Good work, btw!

**Comment by jdkato** [comment]
Is it possible that you could share your `.vale.ini` and the actual markup file? 

As is, the example is hard to read because it appears that you're writing in AsciiDoc but GitHub is trying to render it as Markdown.

**Comment by NicolasMassart** [comment]
Using Vale v2.4.2 here.

This issue needs to have more detail but I may experience something similar with code block and inline code being checked by Vale. Not linked to GitHub action on my side, it also happens locally.

For instance I have ` 41:4     error    Did you really mean 'json'?     Vale.Spelling` when the line 41 is the block start of:
````markdown
```json
"encryptor":{
    "type":"EC",
    "properties":{
        "symmetricCipher":"AES/GCM/NoPadding",
        "ellipticCurve":"secp256r1",
        "nonceLength":"24",
        "sharedKeyLength":"32"
    }
}
```
````

Of course, if I remove the code type on the code block it works for this block, but then fails on the next JSON block. And I require all my blocks to have a code type defined in my Markdown linter to have the correct highlighting, so that's not an option to remove.

Also note that `json` is a word that I have as uppercased `JSON` in an acronym rule that is a copy of the MS one (among other acronyms):

```yaml
extends: conditional
message: "'%s' has no definition."
level: suggestion
ignorecase: true
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\b([A-Z]{3,5})\b'
second: '(?:\b[A-Z][a-z]+ )+\(([A-Z]{3,5})\)'
# ... with the exception of these:
exceptions:
  ...
  - JSON
  ...
```

But this doesn't change anything.

However if I add `JSON` in the `accepted.txt` I have the following error:
`41:1     error    Use 'JSON' instead of 'json'.   Vale.Terms` meaning `Vale.Terms` looks in the code block.

If I add `json` in my `accepted.txt` Vocab, then I don't have the issues on code blocks but it's not good as I expect writers to use `JSON` everywhere in the text.

This then conflicts with the acronym rule as it says for instance `109:17   error    Use 'json' instead of 'JSON'.   Vale.Terms` and I don't want that, I want the uppercased acronym to be used.

Let me know if you need more testing from me.

**Comment by jdkato** [comment]
I'm going to close this for now, but feel to comment further.
