### ISSUE TITLE
url in link fires capitalization rule

### ISSUE THREAD

**Issue by stalsma** [vale-cli/vale#276]
Testing with Vale 2.6.2 from homebrew (macOS).

I am enforcing sentence-style capitalization in lists:
```
extends: capitalization
message: "'%s' should use sentence-style capitalization."
level: suggestion
scope: list
match: $sentence
indicators:
  - ':'
```

But when the list item contains a links whose text is the website url itself, the period in the link text triggers a new sentence.

E.g.
`<li><a href="">www.website.com</a></li>`
>  190:20   suggestion  'www.website.com' should use sentence-style capitalization. 

I can also confirm a non-unicode ellipsis `...` causes the same error.
>  191:20   suggestion  '...' should use sentence-style capitalization.   

I dug around a bit in the go code (not knowing go), and I think the issue is in `variables.go`.  The strings are delimited on punctuation, (and the `TrimRight` removes the delimiting space?).  But I suspect the delimiter itself is at issue.  Shouldn't sentences be delimited by the punctuation plus any whitespace? `[\?!\.:]\s+`

```
func sentence(s string, ignore []string, indicators []string, except *regexp.Regexp) bool {
	count := 0.0
	words := 0.0

	re := makeExceptions(ignore)

	tokens := re.FindAllString(strings.TrimRight(s, "?!.:"), -1)
```

**Comment by jdkato** [comment]
This is expected behavior (and has nothing to do with sentence segmentation; the `sentence` name refers to the capitalization style but doesn't actually involve splitting sentences).

The list entry `<li><a href="">www.website.com</a></li>` *doesn't* follow sentence-style capitalization and *should* raise an alert. You could write it as any of the following:

- `<li><a href="www.website.com">Website</a></li>`

- `<li><a href="www.website.com"><code>www.website.com</code></a></li>`

- `<li><a href="www.website.com">website</a></li>` (if "website" is listed as an exception).

This is also true for `...`, which is simply not a valid sentence-cased heading.
