### ISSUE TITLE
Ignore substitution in adoc anchors

### ISSUE THREAD

**Issue by rorokaloom** [vale-cli/vale#281]
Hello,

More of a question:

Using adocs in my vale.ini: 

```
# Only adoc files
[*.adoc]
```

And using a substitution rule:

```
extends: substitution
message: Consider using '%s' instead of '%s'
level: warning
ignorecase: false
# swap maps tokens in form of bad: good
swap:
  tweak: Tweak
```

What would be the best approach to ignore Asciidoc anchors, as all my anchors are lowercase:
`
[#tweak]`

I tried using BlockIgnores and TokenIgnores to no avail.
`TokenIgnores = (?s) *(\[#.*?\])`

**Comment by jdkato** [comment]
Could you provide an example file where this is necessary? In general, you shouldn't need to ignore standard markup syntax.

**Comment by Thourum** [comment]
I had a similar problem, I tried ignoring `org-mode` comments that start with `#+` and so I tried to use 
`TokenIgnores = (#\+.+)`

I Also try to escaping it like `(\#\+.+)` or `"(#\+.+)"` but none of them worked. So I tried using `vale ls-config` to see the output of the **TokenIgnores** in JSON that look like 
``` json
  "TokenIgnores": {
    "*.org": [
      "("
    ]
  },
``` 
I realized it wasn't escaping it so after a bit of looking around I find that it was not escaping because Go-ini thought it was an inline comment. Luckily there was an easy fix, that was replacing a line [ini.go#L208](https://github.com/errata-ai/vale/blob/v2/source/ini.go#L208) 

``` go 
uCfg, err = ini.ShadowLoad(base)
``` 
``` go
uCfg, err = ini.LoadSources(ini.LoadOptions{
		AllowShadows:             true,
		SpaceBeforeInlineComment: true}, base)
```

That **SpaceBeforeInlineComment** requires a space before `#` or `;` to count as an inline comment.

Using this build of vale and `TokenIgnores = (#\+.+$)` results in 
``` json
  "TokenIgnores": {
    "*.org": [
      "(#\\+.+$)"
    ]
  },
```

Unfortunately, even though I've managed the fix this little parsing problem I'm still unable to ignore the whole line that starts with `#+` but I hope someone might find this useful anyway.

**Comment by rorokaloom** [comment]
@jdkato 
Essentally the Asciidoc file would look like:

```
[#heading_title_test]
== Heading Title Test

Text...
```

Each one of my headings `Heading Title Test` in this example has an anchor just above it starting with `[#` and ending with `]`. The convention we use is to use the heading title while spaces being substituted with underscores as the anchor name.

If I'm substituting as follows:

```
...
swap:
  test: Test
...
```
How would I ignore the content staring `[#` and ending with `]`? Currently vale reports it as an error, can you please suggest a method to do this?

**Comment by jdkato** [comment]
This should happen automatically: given the rule

```yaml
extends: substitution
message: "Use '%s' instead of '%s'"
level: error
swap:
  test: Test
```
and the test document

```asciidoc
[#heading_title_test]
== Heading Title Test

This is a test sentence.

[#test]
=== Another test

This is another test sentence.
```

I get the expected results:

![Screen Shot 2020-12-07 at 1 11 44 PM](https://user-images.githubusercontent.com/8785025/101406028-c913e300-388d-11eb-9ff6-bbf8cbc7a07d.png)
