### ISSUE TITLE
Inconsistent quoting with %s substitution in messages .

### ISSUE THREAD

**Issue by ghost** [vale-cli/vale#282]
## Environment

* Windows 10
* Installed via Chocolatey
* vale version 2.6.4

## Summary

* Messages in `existence` rules **do not** surround %s variables with single quotes.
* Messages in `substitution` rules **do** surround the replacement value(s) in single quotes, but **do not** surround the offending text value.

## Test case example

* Standalone test case located here: <https://github.com/dfinr/vale-test-cases/tree/main/inconsistent%20messages>

        PS > .\test.ps1

_Result: (%s variables have bold added for easier identification)_

testMarkdown.md:3:18:MyRules.Substitutions:Use "**'administrator'**" instead of "**admin**."
testMarkdown.md:3:101:MyRules.Avoid:Please avoid oxymorons such as "**exact estimate**."
testMarkdown.md:3:158:MyRules.Substitutions:Use "**'import'** or **'load'**" instead of "**ingest**."

**Comment by jdkato** [comment]
The behavior here depends on if your `substitution` rule includes

```yaml
action:
  name: replace
```
or not. If it does, the replacements need to be programmatically accessible so that Vale Server can offer them as 'fixes' in text editors (e.g., VS Code):

```yaml
extends: substitution
message: "Use %s instead of '%s'"
level: error
ignorecase: false
action:
  name: replace
swap:
  match: option 1|option 2
```

becomes 

> Use 'option 1' or 'option 2' instead of 'match' 

where the options are quoted individually. If you don't include the action, no formatting or parsing is performed.

I'll try to make this more clear in the docs.

**Comment by ghost** [comment]
Excellent! Thank you, I appreciate the clarification.

**Comment by jdkato** [comment]
I'm going to keep this open as a reminder to update the docs on this.
