### ISSUE TITLE
Vale should ignore xref target (even when the macro has no attribute)

### ISSUE THREAD

**Issue by ggrossetie** [vale-cli/vale#297]
- OS: Linux 
- Install method: Direct download
- Vale version: `vale version 2.6.8`

`.vale.ini`

```ini
StylesPath = docs/.vale
MinAlertLevel = suggestion

[*.adoc]
BasedOnStyles = test
```

`docs/.vale/test/Substitutions.yml`

```yml
extends: substitution
message: Consider using '%s' instead of '%s'
level: error
ignorecase: true
swap:
  ruby: Ruby
```

`docs/test.adoc`

```adoc
= Document Title

Head over to xref:ruby.adoc[].
```

#### Current result

```console
$ vale docs/test.adoc

 docs/test.adoc
 3:19  error  Consider using 'Ruby' instead   test.Substitutions 
              of 'ruby
```

#### Expected result

I would expect the target of the `xref` to be ignored by Vale.

`xref` does not necessarily have attribute. In some context, the xref text can be inferred so it's actually a good practice to not explicitly define a cross reference text.

**Comment by jdkato** [comment]
See #298.

**Comment by ggrossetie** [comment]
I see, Vale is working on the generated HTML so it does not know that the cross-reference does not have an associated text.

The problem is that the built-in HTML 5 converter does not make any distinct so I cannot use `IgnoredClasses`. For reference, the generated HTML will be:

```html
<a href="ruby.adoc">ruby.adoc</a>
```

One way to solve this issue would be to provide a custom converter where we could add a class when the xref does not have any associated text.

I understand that Vale is not aware of the `xref` macro but I still think we should try to find a solution in order to provide a great user experience when working with AsciiDoc.

**Comment by jdkato** [comment]
I think the problem here is not that the cross-reference lacks associated text; it's that its default associated text is violating the provided rule.

To me, this seems like a fair (and consistent) result from Vale: in this case, the text "ruby.adoc" is indeed both reader-facing and a rule violation.

A reasonable solution here would be to provide label text that doesn't violate the style guide.

Similarly, while you *could* use `IgnoredClasses` in #298, I would argue that a better solution would be to not use a bare link.

**Comment by ggrossetie** [comment]
Actually, the associated text will be resolved by the site generator. In this case, it will use the document title of the file ruby.adoc.

My point is that Vale should not apply rules on the URL of the linked resource.

What about ignoring the text of the link if the value is equals to the `href` attribute? I think that's what most people will expect.
If we want to give extra control we could still provide an option to disable this feature?

**Comment by jdkato** [comment]
> Actually, the associated text will be resolved by the site generator. In this case, it will use the document title of the file ruby.adoc.

The behavior I described is *exactly* what happens from Vale's perspective. You can easily verify this by running `asciidoctor` on your provided snippet.

> My point is that Vale should not apply rules on the URL of the linked resource.

I've tried to say this multiple ways already, but this *is not* what is happening. Vale is linting the text of the reference, not its URL.

---

I'm not trying to be argumentative here, but I think it's fair to say that:

1. Vale already does *a lot* to accommodate markup formats. In addition to attempting to support multiple out-of-the-box, it offers the ability to [ignore in-document tokens](https://docs.errata.ai/vale/scoping#non-standard-markup) according to a regex and allows you to turn off certain rules [through in-document comments](https://docs.errata.ai/vale/scoping#markup-based-configuration).

2. This isn't a case of handling markup incorrectly; link text is linted under all circumstances.

3. The actual case presented here is pretty contrived and could be resolved by (1) changing the word boundary of the rule in question, (2) selectively disabling the rule with an in-text comment, or (3) changing the link's label.

**Comment by ggrossetie** [comment]
> The behavior I described is exactly what happens from Vale's perspective. You can easily verify this by running asciidoctor on your provided snippet.

Yes, that's true.
My point is that a site generator can provide additional context when converting the exact same AsciiDoc file to HTML.
For instance, when using Antora, `xref` will be resolved from a content catalog and the link will be:

```html
<a href="ruby.adoc">Document Title of Ruby.adoc</a>
```

The reason is that Antora is working on a catalog of files whereas Asciidoctor is working on one file at a time.
In other words, `asciidoctor` cannot resolve `ruby.adoc` because the processor is not aware of this file but Antora can.


> I've tried to say this multiple ways already, but this is not what is happening. Vale is linting the text of the reference, not its URL.

Sorry, I wasn't clear.
Vale will not lint the `href` attribute but since the text of the link is equals to the `href` attribute we are quite sure that the text is actually an URL.

Let's take an example:

```html
<a href="https://www.google.fr">https://www.google.fr</a>
```

Vale will not lint the `href` attribute but it will still lint the text of the link which is `https://www.google.fr`.


> Vale already does a lot to accommodate markup formats. In addition to attempting to support multiple out-of-the-box, it offers the ability to ignore in-document tokens according to a regex 

This could work but I still believe we should provide this behavior by default.


> and allows you to turn off certain rules through in-document comments.

In my opinion, in-document comments seem a bit excessive and will deteriorate readability:

**before**
```
Asciidoctor has both a xref:asciidoctor:cli:index.adoc[] and an xref:asciidoctor:api:index.adoc[] that you can use to...
```

**after**
````
Asciidoctor has both a
pass:[<!-- vale asciidoc.Substituions = NO -->]
xref:asciidoctor:cli:index.adoc[]
pass:[<!-- vale asciidoc.Substituions = YES -->]
and an
pass:[<!-- vale asciidoc.Substituions = NO -->]
xref:asciidoctor:api:index.adoc[]
pass:[<!-- vale asciidoc.Substituions = YES -->]
that you can use to...
````

> This isn't a case of handling markup incorrectly; link text is linted under all circumstances.

I agree Vale is handling markup correctly.
My proposal is simply to ignore link texts when the value is equals to the `href` attribute.

**Comment by jdkato** [comment]
> I agree Vale is handling markup correctly.

While I think this is really all there is to say here, I'll try to explain my reasoning one more time.

Firstly, and perhaps most importantly, I'm not trying to be argumentative or to stifle contributions to Vale. I think it's clear from past issues and PRs that the opposite is generally true: I try to accommodate the needs of everyone. In some cases, though, disagreements from otherwise well-meaning parties are going to happen. And I think this is one of those cases.

## The "problem"

The issue here is relatively simple: In a snippet like `<a href="ruby.adoc">ruby.adoc</a>`, Vale will ignore the URL but lint the text of the link (which in this case is equal to the `href`). 

## The proposed solution

The proposed solution is to hard-code logic into Vale that ignore's link text when it matches the `href` value.

I dislike this solution for three reasons:

1. The existing behavior is technically correct; the text of a link *should* be linted.

2. The proposed solution is an attempt to make Vale support generator-specific functionality. The issue isn't that Vale is doing something wrong; it's that that "problem," so to speak, is being solved by a site generator.

    The best "solution" here would be to simply provide text for the link (for example, `Head over to xref:ruby.adoc[My Document on Ruby]`). This can't be done, though, be Antora performs its own substitution (which is effectively hidden from Vale).

    This is not a unique situation&mdash;most of the existing solutions (discussed below) were created to accommodate generator-specific syntax or functionality: Hugo has its own syntax for code blocks, Jekyll allows you to write inline math, and so on. Attempting to make all of these cases "work" without using one of the existing generator-agnostic solutions simply isn't sustainable.

3. There are many, many ways to "fix" this already.

## The available solutions

1. Provide text for the link. This is the correct, format-agnostic solution here.

2. Use an in-text configuration comment to selectively disable the rule:

    ```adoc
    pass:[<!-- vale asciidoc.Substituions = NO -->]

    Asciidoctor has both a xref:asciidoctor:cli:index.adoc[] and an xref:asciidoctor:api:index.adoc[] that you can 
    use to do stuff.

    pass:[<!-- vale asciidoc.Substituions = YES -->]
    ```

3. Alter the [default word-boundaries](https://docs.errata.ai/vale/config#wordtemplate) to accommodate for your "bare links": `WordTemplate = \s(?:%s)\s`.

4. Alter the word boundaries for just the rule in question:

    ```yaml
    extends: substitution
    message: Consider using '%s' instead of '%s'
    level: error
    ignorecase: true
    nonword: true
    swap:
      '\sasciidoctor\s': Asciidoctor
    ```

5. Use [`TokenIgnores`](https://docs.errata.ai/vale/scoping#non-standard-markup) to ignore a certain pattern.

6. Use [`IgnoredClasses`](https://docs.errata.ai/vale/config#ignoredclasses-v22) to ignore a certain class associated with "bare links".

7. Run Vale on the Antora-generated HTML.

All of these solutions were built for cases like this one. They don't (1) modify the AST, (2) change existing (correct) behavior, or (3) target a specific generator.

--- 
 
Finally, at this point, I think we should both be able to agree that this issue has been discussed enough. It's no longer productive for either of us.

**Comment by ggrossetie** [comment]
I mostly agree with what you said just a note:

> The proposed solution is an attempt to make Vale support generator-specific functionality

That's not true, we have the same "issue" with bare links which is format agnostic (Markdown, AsciiDoc...)

> The available solutions

Thanks for taking the time to describe each solutions :+1:

**Comment by ggrossetie** [comment]
> Use TokenIgnores to ignore a certain pattern.

@jdkato I'm using the following definition but it does not seem to work:

```ini
StylesPath = docs/.vale
MinAlertLevel = suggestion

[*.adoc]
BasedOnStyles = test
TokenIgnores = (xref:[a-z.-]+\[\])
```

(My regular expression seems correct, I'm using https://regex101.com)

**docs/nav.adoc**
```adoc
xref:ruby-setup.adoc[]
```

**docs/.vale/test/Substitutions.yml**
```yml
extends: substitution
message: Consider using '%s' instead of '%s'
level: error
ignorecase: true
nonword: false
scope: text
swap:
  ruby: Ruby
```

```
$ vale docs/nav.adoc 

 docs/nav.adoc
 1:6  error  Consider using 'Ruby' instead   test.Substitutions 
             of 'ruby'                                          

✖ 1 error, 0 warnings and 0 suggestions in 1 file.
```

Did I miss something? Should I report a bug?

EDIT: I just noticed that the project has "discussion" enabled (https://github.com/errata-ai/vale/discussions). Should I ask over there?
