### ISSUE TITLE
URL handling

### ISSUE THREAD

**Issue by th0ger** [vale-cli/vale#317]
Suppose we want to enforce that `Google` (as product and company) is always with uppercase G , but it's domain may be written in lowercase.
I fact, we want all readable URLs to be in lowercase.

So I add `Google` to my `accept.txt` vocabulary.
But this means that this:

```
Visit Google on [www.google.com](https://www.google.com).
```
will throw a `Use 'Google' instead of 'google'` on the url text.

What is the recommended way to handle this?

I know that [it is common to use text as links](www.dummy.com), but sometimes the bare hostname is a better option.

```
=== .vale.ini ===
StylesPath = styles
MinAlertLevel = suggestion

Vocab = myVocabulary

[*.{md,rst}]
BasedOnStyles = Vale
```

**Comment by jdkato** [comment]
I would put the URL in a code span: 

```markdown
[`www.google.com`](https://www.google.com)
````

**Comment by th0ger** [comment]
That doesn't work, my html displays:
```
``https://www.google.com` <https://www.google.com>`_
```

**Comment by jdkato** [comment]
I can assure you that it *does* indeed work with Markdown content. 

The problem here seems to be a misunderstanding about markup formats: 

1. Your example link syntax (`[...](...)`) is Markdown;
2. your post immediately above contains an (invalid) reStructuredText link; and
3. you're referring to "my html".

Based on #316, my guess is that you're writing the Markdown-style link in a file that is being converted to reStructuredText&mdash;which doesn't support nested markup the way Markdown does.

My guesswork aside, it seems that my suggestion "doesn't work" for you because you're effectively using an unsupported markup format (your Markdown / reStructuredText mixture).

I don't think there's much I can do to help here: Vale does a lot to support common markup formats, but it doesn't support mixing them in non-standard ways (which I think is understandable).
