### ISSUE TITLE
Option to ignore specific files that should not be changed (eg licenses)

### ISSUE THREAD

**Issue by RCheesley** [vale-cli/vale#347]
Hi folks!

I have read the previous issues regarding excluding specific files and wanted to share a use case where I feel this is valid.

We have Vale set up on a WIP PR on our Grav-based docs, and it is running on .md files which is perfect. On our docs, one of these pages is the Apache license relating to our documentation, rendered on the front end in an .md file, which we cannot and should not modify.  Furthermore, that license itself is triggering errors:

> Don't use plurals in parentheses such as in 'Contribution(s)'.

Despite trying to [add that to our vocab](https://github.com/mautic/mautic-documentation/pull/147/files#diff-0c78a72bedc3a28cc07414a92bf4e984be7776e79202899cd0117095ecb9af88R13) it continues to throw errors (maybe an error on our part - if so please do let me know!).

I want to keep that (valid) rule in Vale, however we do **not** want to even be checking licences because they should not be modified by the linter, yet they are required to be present and in the same format as our docs pages.

I guess that we could hack around it by adding a class to the page and ignoring on that basis however I feel it would be a more elegant solution to simply provide a path that should be ignored by the linter.

**Comment by jdkato** [comment]
You can achieve this a number of ways:

1. By passing an appropriate [`--glob`](https://docs.errata.ai/vale/cli#--glob) pattern&mdash;for example,

    ```console
    $ vale --glob='!*/03.License/*' pages 
    ```

2. By completely disabling Vale on the file by adding `<!-- vale off -->` at the top (see [in-text comments](https://docs.errata.ai/vale/scoping#markup-based-configuration)).

3. By disabling a specific rule (such as `<!-- vale Google.OptionalPlurals = NO -->`) at the top of the file.

I wouldn't recommend using `IgnoredClasses` for Markdown, though, since it requires wrapping content in otherwise unnecessary HTML tags.

**Comment by RCheesley** [comment]
OK thank you for the guidance - much appreciated!
