### ISSUE TITLE
Feature request: way to manage globally installed rule sets

### ISSUE THREAD

**Issue by keenahn** [vale-cli/vale#39]
Hello! I just learned about vale and am very excited about it. The first thing I noticed is that when you install from `brew install vale` it just provides the compiled bin with none of the optional rule sets. My workaround is to currently clone the entire vale repo and add 

`StylesPath = xxxxxx/vale/styles` in my `$HOME/.vale` 

It would be cool if the distribution shipped with these styles. If they do and I'm not seeing it, please correct me. I'm going to be working off the source version for now.

**Comment by jdkato** [comment]
Hi,

Thanks for trying out Vale!

As you suspected, the optional styles aren't currently shipped via Homebrew or the standalone downloads (the default style, `vale`, is included though).

I agree that it should be easier to download them, but I'd prefer to avoid shipping all of them with the binary since I think most people won't need that. I was thinking, instead, about taking an approach similar to [Bootstrap Table](http://bootstrap-table.wenzhixin.net.cn/extensions/): have a searchable list of extension styles hosted at https://valelint.github.io/.  This way, as the list grows, someone could search for something like "technical writing" or "job applications" and receive a list of relevant downloadable styles (perhaps as `.zip`  files). 

What do you think of this idea?

**Comment by jdkato** [comment]
In the meantime (before I get a chance to work on the website), I've added download links to the README.

**Comment by jdkato** [comment]
This discussion should move to https://github.com/ValeLint/docs/issues/1.
