### ISSUE TITLE
Referencing key matches in values for swaps

### ISSUE THREAD

**Issue by abingham** [vale-cli/vale#45]
I'm working on a style to standardize some books on Python, and one place I need consistency is how I talk about "blocks" in the language. I want vale rules to make sure I use "for-block" rather than "for block", "`for`-block", or "`for` block". I want similar rules for "if-block", "else-block", and every other kind of block I might need to talk about.

Conceptually, I want swap rules like this:
```
(for|if|try|else) block: \1-block
`(for|if|try|else)`(?: |-)block: \1-block
``` 
That is, I want to capture the type of block in the key regex and reference it in the value. As far as I can tell, this isn't supported in vale. Am I wrong and there's actually a way to do this?

If I'm right, would it be possible to add this?

This is far from critical for me, and it's probably a bit of an edge-case for most users. I can always just enumerate all of the different rules.

**Comment by jdkato** [comment]
As you suspected, there's currently no way to do this without writing a more generic message (e.g., something like `Prefer '<keyword>-block' over 'if block'`, where "if block" is the match).

And while I think it would be a nice addition, the issue is that the individual swap rules are currently converted into a single pattern (for performance reasons) under the hood. This makes it more difficult to keep track of what capture group `\1` actually refers to.

That said, message customization is definitely something that I'd like to improve&mdash;it's just a matter of finding a balance between usability and performance (especially since rule evaluation is very much a "hot path" task).

**Comment by abingham** [comment]
OK, I figured there were good reasons for the current state. What I've done is to write a Python script that generates the rules, and this seems to work well.

Though on that note: what about letting users express rules in Python (or ruby or whatever...any proper programming language)? These scripts could sit right next to the existing yaml files, and Vale could run those to compile the yaml rules. I'm not necessarily recommending this, esp. as I think my use-case is pretty rare, but it might be a useful "power tool" for some users.

I'll go ahead and close this. Thanks for the quick response!

**Comment by jdkato** [comment]
Supporting external scripts has actually been a goal of mine since the start. In fact, there was unofficial support for this until v0.5.0 using the following extension style:

```yaml
extends: script		
scope: text		
runtime: node		
exe: check_spelling.js 
```
where `check_spelling.js` was, for example, a Node.js script that called Atom's [SpellChecker](https://github.com/atom/node-spellchecker) module. There are a number of details that I need to iron out, but it's definitely in the works.
