### ISSUE TITLE
Feature: Support environment variable for vale.ini location

### ISSUE THREAD

**Issue by sdwheeler** [vale-cli/vale#576]
I have a default configuration that I want vale to use without the need to specify the location.

Add an environment variable (eg. `VALE.INI` or just `VALE`) that contains the location of my default vale.ini file. If `--config` isn't specified check for the environment variable. 

- The workspace ini file should take precedence over the file specified by the environment variable.
- The command-line option should always take precedence over the environment setting or workspace ini file.

**Comment by bollwyvl** [comment]
Inverting this, it would be lovely if a well-known `VALE_STYLES` environment variable, [XDG dirs](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), etc. could be checked for named styles, dictionaries, etc. and resolved without `sync`.

Alternately, arbitrary variables could be expanded in `vale.ini`.

Either approach would be useful for fully-packaged, offline-ready styles that didn't rely on `sync` to be downloaded at runtime, and using package-manager style semantics (instead of e.g. submodules) to keep a set of styles managed in a less bespoke way.

**Edit:** didn't scroll far enough: something related was already suggested on #295.

**Comment by jdkato** [comment]
In the next release, you'll be able to set `--config` with the variable `VALE_CONFIG_PATH`.

> The workspace ini file should take precedence over the file specified by the environment variable.

This will not be the case, though: it will work the same as `--config`. The precedence is `--config`, `VALE_CONFIG_PATH`, default search process.
