### ISSUE TITLE
How to disable Vale.terms from checking link hrefs

### ISSUE THREAD

**Issue by nickvigilante** [vale-cli/vale#582]
https://github.com/cockroachdb/docs/pull/16365/files#diff-d4e9241f5b16c37527034daf11a35f169348066d93483c9524a21267afa43aaeR30

Is there any way to get Vale.terms to stop checking link hrefs? It's a valid URL, and it's making a lot of extra noise. Thanks!

**Comment by jdkato** [comment]
Ignoring URLs is the default behavior. If you're seeing an issue, it's almost certainly related to custom configuration.

In your case, you have `(\{%.*?%\})|(\{\{.*?\}\})` listed in *both* `BlockIgnores` and `TokenIgnores`, which causes two problems:

1. There shouldn't be overlap between these -- it could easily result in invalid markup.
2. Since the Liquid tags can appear inline, they should only be ignored through `TokenIgnores`.

**Comment by nickvigilante** [comment]
Hey @jdkato, I'm at a new company, and I'm also noticing this with a vanilla configuration:

In `vale/config/vocabularies/TileDB/accept.txt`:

```
TileDB
```

`.vale.ini`:

```
StylesPath = vale

Vocab = TileDB

MinAlertLevel = suggestion

[*]
BasedOnStyles = Vale
```

`some-file.qmd` ([Quarto](https://quarto.org/) Markdown file):

```
---
title: "Sample"
---

[TileDB](https://tiledb.com)
```

Result:

```
vale some-file.qmd 

 some-file.qmd
 5:18  error  Use 'TileDB' instead of         Vale.Terms 
              'tiledb'.                                  

✖ 1 error, 0 warnings and 0 suggestions in 1 file.
```

If I rename the extension to `.md`, it works fine, but we use the `.qmd` extension to leverage Quarto's additional features. Would it be possible to add this extension to the list of supported extensions? I've disabled `Vale.Terms` to work around the issue. Let me know if I should log another ticket.

**Comment by nickvigilante** [comment]
NVM, solved my own issue by adding this to `.vale.ini`:

```
[formats]
qmd = md
```

Thanks!
