### ISSUE TITLE
Cannot make vale ignore checking inside <screen/> element in DocBook

### ISSUE THREAD

**Issue by tbazant** [vale-cli/vale#622]
### Check for existing issues

- [X] Completed

### Environment

Linux, manual git checkout, Vale plugin in VSCode

### Describe the bug / provide steps to reproduce it

In our DocBook XML files, we use the &lt;screen/> element to print unmodified content of a terminal window, for example. We don't want vale to check inside &lt;screen/> at all, better ignore it completely. This element transforms into &lt;pre class="screen"/> by XSL stylesheet.
I've tried
`IgnoredScopes = screen, pre`
or
`IgnoredClasses = screen`
but to no success.
Any idea how to solve this?

![image](https://user-images.githubusercontent.com/2240174/236449586-0f108bd7-d0c5-4930-a66d-8f6400374364.png)

**Comment by jdkato** [comment]
You're providing the XSL stylesheet to Vale, right?

Can I see your `.vale.ini`?

**Comment by tbazant** [comment]
Sure, here it is
```
StylesPath = /home/tbazant/devel/
MinAlertLevel = suggestion
[asciidoctor]
experimental = YES
[*.xml]
Transform = /usr/share/xml/docbook/stylesheet/suse2022-ns/xhtml/docbook.xsl
BasedOnStyles = suse-vale-styleguide
[*.{md,txt,adoc}]
BasedOnStyles = suse-vale-styleguide
```

**Comment by jdkato** [comment]
`pre` elements are ignored by default, so there's no extra config (`IgnoredScopes`, `IgnoredClasses`, etc.) required.

The issue here is that your rule [`Colons.yml`](https://github.com/openSUSE/suse-vale-styleguide/blob/main/Colons.yml) specifies `scope: raw` which bypasses the markup transformation altogether. In other words, you should only use `scope: raw` when you *want* a rule to apply to markup syntax or ignored elements.
