### ISSUE TITLE
[feature request] Add option for "fix"

### ISSUE THREAD

**Issue by nschonni** [vale-cli/vale#70]
Searched the issue tracker first and didn't find anything, so hopefully I'm not repeating.

For some of the error rules, it seems like Vale should be able to heal/fix like ESLint does for certain rules.
Mainly I'm thinking about the case for `vale.Repetition`, but I think there may be other non-ambiguous rules that might benefit.

**Comment by jdkato** [comment]
While this would no doubt be convenient for some, I'm personally not a fan of the idea. I think writing is far too nuanced to be "automatically" fixed by any tool, let alone one that primarily focuses on *style*. Even a rule like `vale.Repetition` has a number of edge cases (e.g., "had had" and "that that").

That said, this can be done fairly easily by using Vale's `--output=JSON` option and a scripting language. There's a somewhat related example of this in #69.

**Comment by nschonni** [comment]
Sorry for the late response. I can see how the false positives might be an issue. My motivation was mostly for trying to fix up repos for the first time, but I guess there might be a pattern with the JSON output you mentioned
