### ISSUE TITLE
Not finding Styles directory on Windows with latest version(s)

### ISSUE THREAD

**Issue by DanDiplo** [vale-cli/vale#82]
I have the following set-up on Windows (64bit). I have downloaded the 1.0.3 Windows 64 exe (without installer) and have it in a directory setup like this:

`/vale.exe`
`/_vale.ini`
`/Styles/Joblint/*.yml`

In my `_vale.ini` I have the styles path configured like this:

`StylesPath = "Styles"`

In the previous version I was using, which was **v0.11.2**, then this worked. If I type `vale dc` I would get:

` "StylesPath": "C:\\Projects\\Vale\\Styles"`

Vale picked up the Styles folder fine.

But in all the **V1.0.x** releases the `StylesPath` is not read. It is empty:

` "StylesPath": ""`

I have custom .yml files in the `C:\Projects\Vale\Styles\Joblint\` folder that are not read in latest version, but where picked up in the older version. If I swap back to the older .exe it all works and the custom styles are picked up.

Could you shed any light on this? For deployment reasons I really don't want to have to have the full path but use a relative one. How do I get Vale to read the Styles path as a relative path to the .exe and .ini ? Thanks.

**Comment by jdkato** [comment]
I have two thoughts:

1. My guess is that your styles are actually being loaded, but they're not showing up in `dc` (due to the command occasionally firing before Vale can load its configuration). This was fixed recently in 3e118bf5a70928a359adbb9b5fa48ca8b468df1f and will be available in the next release.
2. In v1.0.0 and later, `Joblint` is included with Vale&mdash;meaning you should avoid using the same name for custom styles (the same goes for `proselint`, `vale`, and `write-good`).

Have you tried calling Vale on a file that violates your style? I ran a simple test using Windows 8/Git Bash and received the expected results (ignoring the aforementioned `dc` issue):

```
$ ls
_vale.ini  Styles/  test.md  vale.exe*
$ ls Styles
Test/
$ cat test.md
Hey dude!
$ cat _vale.ini
StylesPath = "Styles"

[*]
BasedOnStyles = Test
$ ./vale.exe test.md
1:5  error  Don't use 'dude'  Test.Simple
```

**Comment by DanDiplo** [comment]
Hi Joseph. Thanks for responding so quickly.

I tried renaming the directory `JobLint` to a different name and this resolved the issue of Vale not picking up the custom styles I'd added to that directory. I never realised that Vale had the JobLint styles "baked in" to the code. So, as you say, it must have been using these built-in styles rather than the ones in my folder. The "dc" issue must be a red-herring in this case!

I'd maybe suggest that Vale would give priority to files it finds on disk over those built-in as it would avoid this confusion, though you may have your reasons.

Anyway, thanks for an awesome product - I've been very impressed with how it performs and how easily it can be configured. I'll leave it to you to close the issue if you believe this is resolved (I'm happy!).

**Comment by jdkato** [comment]
> I'd maybe suggest that Vale would give priority to files it finds on disk over those built-in as it would avoid this confusion, though you may have your reasons.

That's a fair point -- at the least, it should probably give some indication that there's a conflicting style.

I'll leave this open for now as a reminder to improve this behavior.
