### ISSUE TITLE
Julia files `.jl` no longer allowed?

### ISSUE THREAD

**Issue by kellertuer** [vale-cli/vale#881]
### Check for existing issues

- [X] Completed

### Environment

Mac OS, vale 3.7.0 via homebrew

### Describe the bug / provide steps to reproduce it

I just wanted to get back to vale (after not having used it for a while). I have it set up to check my Jluia files (`.jl`) and have not changed the config. However, vale now reports

```
❯ vale .
unsupported extension: '.jl'
```

For my current config see https://github.com/JuliaManifolds/Manopt.jl/blob/kellertuer/modularize-docstrings/.vale.ini

Did I miss some change that might have cause that?
What do I have to do to get them back as allowed ones?
It would be nice to have a good place to see such breaking changes.

**Comment by jdkato** [comment]
This will be fixed in the next release (as should #838).

Vale now uses [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) instead of regex to parse source code. If you find that too little is linted now for your taste, feel free to contribute additional [queries](https://tree-sitter.github.io/tree-sitter/using-parsers#query-syntax) (currently just `block_comment` and `line_comment` are extracted).

**Comment by kellertuer** [comment]
thanks
I will check. My main reason I use it for is actally doc strings (that is blocks of strings upfront a function). So if they are not extracted I might check that and propose a change.
