### ISSUE TITLE
Including and excluding ignore files

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale#92]
OK, here's my next issue / thought. And to recap what I'm trying to create.

I have three spell check configurations with lists of ignore words for certain domains, let's say:

- DevOps terms
- Blockchain terms
- Tech Writing terms

And each of these YAML config files connect to their own ignore.txt file. In my mind this offers modularity as people can enable and disable the checks relative to their domain, but have a good resource for starting checks to use.

Now, this all works, but let's take for example the following nonsense text:

```
Can Ethereum run in a rkt container
```

`Ethereum` is defined as a correct word in the ignore list for Blockchain, and `rkt` for DevOps, but they don't recognise each others words, so of course, each other test picks up the word as incorrect.

Now I'm not sure what can be done about this, if there's a way to configure vale to make this work, or if it goes against intentions somewhat.

I was wondering if there was a way to use the `filters` property to filter terms in the other ignore lists? Or maybe the best approach is to instead switch to using custom aff or dic files? Or a different approach?

Thanks again!

**Comment by jdkato** [comment]
As of now, I don't think there's a good way to support such a workflow:

- `filters` are meant to used as a means of avoiding unnecessary repetition in ignore files. For example, instead of writing an entry for `mysqld`, `mysqldefault`, and `mysqldump`, you could use a filter of `mysql(?:default|dump|d)`.
- Custom `.dic.` and `.aff` files are intended to allow support for other languages or dialects (e.g., British vs. American English).

When implementing the `Spelling` extension point, my expectation was that a given style would only extend it once&mdash;i.e., any enabling and disabling of ignore files would take place at the style level. 

The only way I could imagine something like this working would be to accept an array of ignore files which could then be enabled or disabled within a single `Spelling` rule:

```yml
extends: spelling
message: "Did you really mean '%s'?"
level: error
ignore: 
  - blockchain.txt
  - devOps.txt
  ...
```

Is that along the lines of what you were thinking?

**Comment by ChrisChinchilla** [comment]
@jdkato I think that would work yes, adding and removing items from the ignore list would be relatively easy for users.

**Comment by jdkato** [comment]
This should be ready to go. Let me know if you run into any issues.

**Comment by ChrisChinchilla** [comment]
@jdkato OMG, that's amazing. Fantastic work 🥇
