### ISSUE TITLE
False positive for XML element with false value

### ISSUE THREAD

**Issue by nschonni** [vale-cli/vale#95]
In https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/healthattestation-csp.md
If flags one of the elements as repeated, but there is a value of false inside the element
```
windows/client-management/mdm/healthattestation-csp.md
 1141:3  error  'OSKernelDebuggingEnabled' is   vale.Repetition
                repeated!
```
```xml
     <BootDebuggingEnabled>false</BootDebuggingEnabled>
     <OSKernelDebuggingEnabled>false</OSKernelDebuggingEnabled>
     <CodeIntegrityEnabled>true</CodeIntegrityEnabled>
```

**Comment by jdkato** [comment]
I can't reproduce this with `v1.1.6` (the latest). Are you passing any command-line arguments?

**Comment by nschonni** [comment]
nope, just .vale turning on only the duplicate checks on like in https://github.com/errata-ai/vale/issues/84#issuecomment-428791185

**Comment by nschonni** [comment]
I think the title of this is wrong though since there are other `false` values in that sheet that aren't being flagged

**Comment by jdkato** [comment]
I can reproduce this now (I forgot to disable some of my custom [ignore patterns](https://errata-ai.github.io/vale/formats/#non-standard-markup)). This is actually an interesting edge case to Vale's current markup parsing strategy:

Vale is actually correctly reporting `OSKernelDebuggingEnabled` as being repeated, as it technically is in the following paragraph:

```html
<a href="" id="oskerneldebuggingenabled"></a>**OSKernelDebuggingEnabled**
<p style="margin-left: 20px">OSKernelDebuggingEnabled points to a device that is used in 
development and testing. Devices that are used for test and development typically are less secure: 
they may run unstable code, or be configured with fewer security restrictions required for testing 
and development.</p>
```

After passing the file to Vale's Markdown parser ([`blackfriday`](https://github.com/russross/blackfriday)), the above paragraph is processed as:

```text
OSKernelDebuggingEnabled OSKernelDebuggingEnabled points to a device that is used in development and testing. Devices that are used for test and development typically are less secure: they may run unstable code, or be configured with fewer security restrictions required for testing and development.
```

However, when Vale goes to look for `OSKernelDebuggingEnabled OSKernelDebuggingEnabled` in the source document (i.e., the pre-converted Markdown), it can't find it because `<p style="margin-left: 20px">` is in the way. This forces Vale to fall back to a line-by-line, [Jaro–Winkler](https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance)-based search algorithm, which reports `<OSKernelDebuggingEnabled>false</OSKernelDebuggingEnabled>` as the closest matching line.

I'm not sure that there's anything I can really do about this: going from Markdown to HTML is a pretty straightforward process (and allows Vale to skip code blocks, assign rules to headers, etc., which is something almost no others linters do), but going from HTML-based locations *back* to Markdown is much more difficult. And, with the current strategy, it's nearly impossible to do accurately when there's so much embedded HTML.

My only suggestion at the moment is to find a cleaner way to write `<a href="" id="oskerneldebuggingenabled"></a>**OSKernelDebuggingEnabled**` (which I assume is supposed to be a heading with an anchor?).

**Comment by nschonni** [comment]
Not my docs, I just clean them up as a bedtime meditation :wink: 
I have seen similar ones like you describe for content like
```md
**Administrators**
Administrators do ...
```
This is an incorrect/fakeheading structure that should probably be ripped out.

**Comment by jdkato** [comment]
Indeed -- even adding a blank line like

```text
**Administrators**

Administrators do ...
```
would make it much easier for Vale to parse correctly.

**Comment by nschonni** [comment]
Yeah, probably a definition list would be more appropriate in most of those cases.
