### ISSUE TITLE
Doesn't read file or stdin

### ISSUE THREAD

**Issue by nighthawk9** [vale-cli/vale#99]
I am running Manjaro KDE, up-to-date as of January 7, 2019.

Vale version:  1.2.6

I've have tried the release binary, AUR, and compiling from source. Passing files or text into vale returns only the typical 0 errors, 0 warnings and 0 suggestions in 0 Files (or stdin)

I have not setup a config. Is this required? No error messages. I have attempted to run on README.md files, latex files, plain text files and org files. 

Any help is appreciated.

**Comment by jdkato** [comment]
Yes, setting up a config file is required (by default Vale won't do anything). It's primarily designed to enforce user-created [style guides](https://errata-ai.github.io/vale/styles/), but it also ships with [3 built-in styles](https://github.com/errata-ai/vale#usage) that you can enable.

That said, if it were working correctly, you'd see something along the lines of `0 errors, 0 warnings and 0 suggestions in 1 file`. Can you post the exact command that is returning "0 files" (e.g.,`$ vale README.md`)?

**Comment by nighthawk9** [comment]
I've attempted:

``$ vale README.MD``
``$ vale /home/$USER/Desktop/README.MD``
``$ vale ~/Desktop/README.MD``

I read there was an issue with relative paths at one point in time so I made sure to try the absolute path as well.

I have added a configuration file as needed, and it is working as advertised. I understand that software isn't often made to hold peoples hands, but would it ever be possible to allow vale to generate a default configuration in the future? I don't particularly program in Go, but if there is something I could do I would be glad to help.

**Comment by jdkato** [comment]
All of those examples should work (assuming your shell expands `~` and `$USER`), so I'm assuming the "0 files" was a transcription error?

With regards to making Vale easier to use, I'm always open to suggestions (especially documentation changes), but l'm personally not a fan of providing a default configuration:

- The primary reason for this is that, unlike most other writing-related linters, I never intended for Vale to provide its own advice; I built it as a means of enforcing external style guides. I think ultimately this makes it more useful in many practical situations (e.g., enforcing a house style on a corporate blog, rather than simply reporting the use of passive voice).

- This actually used to exist and I found that many people (see #42, for example) ending up judging the usefulness of the tool based on whatever I chose to include by default. So, in an attempt to promote the intended use case, I've decided to avoid endorsing a particular configuration.

**Comment by nighthawk9** [comment]
When removing the configuration file, it does indeed say 0 files.

I appreciate your response.

![valeconfig](https://user-images.githubusercontent.com/28875131/50928930-2dfffd80-1419-11e9-9845-eaaea00fb078.png)

**Comment by faunaee** [comment]
A possible solution for Vale's unopinionated stance: when there is no configuration file, emit a warning to that effect. Without such a warning, when Vale provides an apparent success message, it makes user believe that Vale is misbehaving/broken.

**Comment by jdkato** [comment]
Yes, I think that's a good idea -- I've started implementing this on the [`refactor/no-config`](https://github.com/errata-ai/vale/tree/refactor/no-config) branch. In the case that Vale fails to locate a config file, it will say something along the lines of:

> WARNING: No configuration file found.
>
> See https://github.com/errata-ai/vale#usage for more information.

This should be included in the next release. I'll close #100 when it's ready.

**Comment by ArtFlag** [comment]
Hi! 
New user here, I was just creating the same issue. 
The idea of a message such as `No config file found, exiting.` will be better than any docs update 👍 
Thanks for this tool!
